name: pocket
description: Tiny Pocket Mobile App

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  intl: ^0.16.1

  provider: ^4.3.2+2

  http: ^0.12.2
  crypto: ^2.1.5
  jwt_decode: ^0.1.0

  pref_dessert: ^0.5.1
  shared_preferences: ^0.5.12+2
  
  simple_animations: ^2.2.3
  page_transition: ^1.1.7+2
  flutter_bloc: ^6.0.6
  fl_chart: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  # ios: true
  android: true
  # image_path_ios: "assets/launcher/icon.png"
  image_path: "assets/pocket.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - ./assets/
   - ./assets/img/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700