name: pocket
description: Tiny Pocket Mobile App

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  provider: ^5.0.0

  http: ^0.13.1
  http_parser: ^4.0.0
  crypto: ^3.0.1
  jwt_decode: ^0.3.1

  pref_dessert: ^0.6.0
  shared_preferences: ^2.0.5
  
  simple_animations: ^3.0.3
  page_transition: ^1.1.7+2
  flutter_bloc: ^7.0.0
  fl_chart: ^0.35.0
  flutter_arc_speed_dial: ^1.0.3
  favicon: ^1.0.14
  animated_dialog: ^1.0.6
  url_launcher: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  # ios: true
  android: true
  # image_path_ios: "assets/launcher/icon.png"
  image_path: "assets/pocket.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - ./assets/
   - ./assets/img/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700